from constants.lexical import KeyWords
LOWEST_PRIORITY_MATH_OPERATORS = [KeyWords.EQUAL, 
    KeyWords.PLUS_EQUAL, 
    KeyWords.MINUS_EQUAL, 
    KeyWords.MULTIPLY_EQUAL, 
    KeyWords.DIVIDE_EQUAL,
    KeyWords.MODULO_EQUAL,
    KeyWords.XOR_EQUAL,
    KeyWords.AND_EQUAL,
    KeyWords.OR_EQUAL,
]
LOW_PRIORITY_MATH_OPERATORS = [KeyWords.EQUALITY, KeyWords.NOT_EQUAL, KeyWords.LESS_THAN, KeyWords.LESS_THAN_EQUAL, KeyWords.GREATER_THAN, KeyWords.GREATER_THAN_EQUAL]
MEDIUM_PRIORITY_MATH_OPERATORS = [KeyWords.PLUS, KeyWords.MINUS]
HIGH_PRIORITY_MATH_OPERATORS = [KeyWords.MULTIPLY, KeyWords.DIVIDE, KeyWords.MODULO, KeyWords.EXPONENT]
HIGHEST_PRIORITY_MATH_OPERATORS = [KeyWords.BOOLEAN_AND, KeyWords.BOOLEAN_OR, KeyWords.XOR]

